# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Inccorpco
email: Null
description: > Welcome to Inccorpco, a free photo sharing website. You can use this to store or create photo albums, create stock photos for public use, and edit your photos. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Null
github_username:  Null

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
